inherits: [iga.yml]
seed: null
stepSize: 1
population:
  type: igastandard
  size: 100
  selection: roulette
  combinepop: elitist
  subset:
    type: best_rand
    size: 12
crossover:
  type: binarytree
  prob: 0.8
  points: 1
mutation:
  type: binarytree
  prob: 0.20
application:
  name: tree_character3d
  vars:
    - name: shape
      max: 1.
      min: 0.
      scale: 1.
    - name: tx
      max: 1.
      min: -1.
      scale: 0.1
    - name: ty
      max: 1.
      min: -1.
      scale: 0.1
    - name: tz
      max: 1.
      min: -1.
      scale: 0.1
    - name: sx
      max: 2.
      min: 0.1
      scale: 0.01
    - name: sy
      max: 2.
      min: 0.1
      scale: 0.01
    - name: sz
      max: 2.
      min: 0.1
      scale: 0.01
    - name: yaw
      max: 20.
      min: -20.
      scale: 1.
    - name: roll
      max: 20.
      min: -20.
      scale: 1.
    - name: pitch
      max: 20.
      min: -20.
      scale: 1.
