inherits: [iga.yml]
seed: null
stepSize: 2
user: user1
peers: ['amit.cse.unr.edu']
population:
  type: igastandard
  size: 50
  selection: tournament
  combinepop: elitist
  subset:
    type: best
    size: 9
crossover:
  type: gen_prog
  prob: 0.7
  points: 1
mutation:
  type: gen_prog
  prob: 0.05
application:
  name: vertex_shader
  vars:
    - name: shape
      max: 3.
      min: 0.
      scale: 1.
    - name: tx
      max: 1.
      min: -1.
      scale: 0.1
    - name: ty
      max: 1.
      min: -1.
      scale: 0.1
    - name: tz
      max: 1.
      min: -1.
      scale: 0.1
    - name: sx
      max: 2.
      min: 0.1
      scale: 0.01
    - name: sy
      max: 2.
      min: 0.1
      scale: 0.01
    - name: sz
      max: 2.
      min: 0.1
      scale: 0.01
    - name: yaw
      max: 20.
      min: -20.
      scale: 1.
    - name: roll
      max: 20.
      min: -20.
      scale: 1.
    - name: pitch
      max: 20.
      min: -20.
      scale: 1.
